# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "ev1l0o4g's blog"
baseURL = "https://www.ev1l0o4g.xyz"
theme = [
  "FixIt",
  "shortcode-docs-bookmark"
]
defaultContentLanguage = "zh-cn"
languageCode = "en"
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
relativeURLs = false
buildDrafts = false
summaryLength = 150
# ignore some build errors
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
